name: Create PR on myrepo

on:
  issue_comment:
    types: [created]

jobs:
  create-pr:
    if: startsWith(github.event.comment.body, 'deploy to') && contains(github.event.comment.body, 'myrepo')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Extract environment and appid from comment
        id: extract
        run: |
          environment=$(echo "${{ github.event.comment.body }}" | grep -oP '(?<=deploy to )[^ ]*' | head -1)
          appid=$(echo "${{ github.event.comment.body }}" | grep -oP '(?<=deploy to [^ ]* )[^ ]*' | head -1)
          echo "::set-output name=environment::$environment"
          echo "::set-output name=appid::$appid"

      - name: Create PR
        run: |
          token=$TOKEN # Replace TOKEN with a personal access token with repo scope
          repo="yourusername/myrepo"
          base="main" # Replace with your target branch
          head="${{ github.event.pull_request.head.ref }}"
          title="Deploy to ${{ steps.extract.outputs.environment }} ${{ steps.extract.outputs.appid }}"
          body="This PR is auto-generated for deploying ${{ steps.extract.outputs.appid }} to ${{ steps.extract.outputs.environment }} environment."
          pr_number=$(curl -X POST -H "Authorization: token $token" -d "{\"title\":\"$title\",\"body\":\"$body\",\"head\":\"$head\",\"base\":\"$base\"}" "https://api.github.com/repos/$repo/pulls" | jq -r '.number')

          echo "::set-output name=pr_number::$pr_number"
